"""
Runner module to invoke the LangGraph pipeline asynchronously.

Takes job parameters, invokes the compiled StateGraph, updates the Job store
on completion or failure, and handles formatting.
"""

from __future__ import annotations

import logging

from api.jobs import mark_complete, mark_error, mark_running
from api.schemas import CoverageReport
from graph.pipeline import compiled_graph

from graph.state import PipelineState

logger = logging.getLogger("script_doctor.graph.runner")


async def run_pipeline(job_id: str, script_text: str, page_count: int) -> None:
    """
    Run the LangGraph pipeline for a specific screenplay analysis job.

    Updates the global jobs store as it progresses and finishes.
    """
    logger.info("Starting pipeline execution for job: %s", job_id)
    mark_running(job_id)

    initial_state: PipelineState = {
        "script_text": script_text,
        "page_count": page_count,
        "job_id": job_id,
        "agent_outputs": [],
        "report": None,
    }

    try:
        # Run graph compiled flow
        final_state = await compiled_graph.ainvoke(initial_state)

        report_dict = final_state.get("report")
        if not report_dict:
            raise ValueError("Pipeline finished but no report was generated by Synthesizer.")

        # Re-parse into the Pydantic schema to validate
        report = CoverageReport.model_validate(report_dict)

        # Mark complete in job store
        mark_complete(job_id, report)

    except Exception as e:
        logger.exception("Pipeline failed for job: %s", job_id)
        mark_error(job_id, str(e))
